TvSerie/config/routes.rb
Rails.application.routes.draw do
  resources :noticions
  resources :serials do
    collection do
      get 'search'
    end
  end
  resources :serials do
  	resources :reviewses
  end
  resources :serials do
    collection do
      get 'search'
    end
    resources :chapters do
      resources :reviewches
    end
  end
  resources :serials do
    resources :chapters do
        resources :vistos
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "serials#index"
end

TvSerie/app/models/noticion.rb
class Noticion < ApplicationRecord
	belongs_to :user
	belongs_to :serial, optional: true 
end

TvSerie/app/controllers/noticions_controller.rb
class NoticionsController < ApplicationController
  before_action :set_noticion, only: [:show, :edit, :update, :destroy]

  # GET /noticions
  # GET /noticions.json
  def index
    @noticions = Noticion.all
  end

  # GET /noticions/1
  # GET /noticions/1.json
  def show
  end

  # GET /noticions/new
  def new
    if current_user != nil
      @noticion = Noticion.new
    else
      authenticate_user!
    end
  end

  # GET /noticions/1/edit
  def edit
    if current_user != nil
      if current_user != @noticion.user and current_user.admin != true
        redirect_to noticion_path(@noticion), notice: 'Usted no es el creador, no puede editarlo' 
      end
    else
      authenticate_user!
    end
  end


  # POST /noticions
  # POST /noticions.json
  def create
    @noticion = Noticion.new(noticion_params)
    @noticion.user_id = current_user.id

    respond_to do |format|
      if @noticion.save
        format.html { redirect_to @noticion, notice: 'Noticion was successfully created.' }
        format.json { render :show, status: :created, location: @noticion }
      else
        format.html { render :new }
        format.json { render json: @noticion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticions/1
  # PATCH/PUT /noticions/1.json
  def update
    respond_to do |format|
      if @noticion.update(noticion_params)
        format.html { redirect_to @noticion, notice: 'Noticion was successfully updated.' }
        format.json { render :show, status: :ok, location: @noticion }
      else
        format.html { render :edit }
        format.json { render json: @noticion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticions/1
  # DELETE /noticions/1.json
  def destroy
    if current_user != nil
      if current_user == @noticion.user or current_user.admin == true
        @noticion.destroy
        redirect_to noticions_path, notice: 'Noticia was successfully destroyed.' 
      else
        redirect_to noticions_path, notice: 'Usted no es el creador, no puede destruirlo' 
      end
    else
      redirect_to noticions_path, notice: 'Usted no esta loggeado, no puede destruirlo'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticion
      @noticion = Noticion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noticion_params
      params.require(:noticion).permit(:titulo, :contenido, :tipo, :serial_id)
    end
end

TvSerie/app/helpers/noticions_helper.rb
module NoticionsHelper
end

TvSerie/app/views/noticions/_form.html.erb
<%= form_for(noticion) do |f| %>
  <% if noticion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(noticion.errors.count, "error") %> prohibited this noticion from being saved:</h2>

      <ul>
      <% noticion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %>
    <%= f.text_area :titulo %>
  </div>

  <div class="field">
    <%= f.label :contenido %>
    <%= f.text_area :contenido %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.select :tipo, ["Estreno", "Nueva Serie", "Avance", "Actores", "Grabacion", "Director"] %>
  </div>
  
  <div class="field">
    <%= f.label :serial_id %>
    <%= f.select :serial_id, [["-",nil]] + Serial.all.collect {|serial| [serial.titulo, serial.id] } , :selected =>f.object[1]  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

TvSerie/app/views/noticions/edit.html.erb
<h1>Editing Noticion</h1>

<%= render 'form', noticion: @noticion %>

<%= link_to 'Show', @noticion %> |
<%= link_to 'Back', noticions_path %>

TvSerie/app/views/noticions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Noticias</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th>Tipo</th>
      <th>Serial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @noticions.each do |noticion| %>
      <tr>
        <td><%= noticion.titulo %></td>
        <td><%= noticion.contenido %></td>
        <td><%= noticion.tipo %></td>
        <% if noticion.serial_id != nil %>
          <td><%= link_to Serial.find(noticion.serial_id).titulo, serial_path(noticion.serial_id) %></td>
        <% else %>
          <td><%= "--" %></td>
        <% end %>
        <td><%= link_to 'Show', noticion %></td>
        <td><%= link_to 'Edit', edit_noticion_path(noticion) %></td>
        <td><%= link_to 'Destroy', noticion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Noticia', new_noticion_path %>

TvSerie/app/views/noticions/new.html.erb
<h1>New Noticion</h1>

<%= render 'form', noticion: @noticion %>

<%= link_to 'Back', noticions_path %>

TvSerie/app/views/noticions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @noticion.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @noticion.contenido %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @noticion.tipo %>
</p>


<%= link_to 'Edit', edit_noticion_path(@noticion) %> |
<%= link_to 'Back', noticions_path %>