TvSerie/config/routes.rb
Rails.application.routes.draw do
  resources :noticions
  resources :serials do
    collection do
      get 'search'
    end
  end
  resources :serials do
  	resources :reviewses
  end
  resources :serials do
    collection do
      get 'search'
    end
    resources :chapters do
      resources :reviewches
    end
  end
  resources :serials do
    resources :chapters do
        resources :vistos
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "serials#index"
end

TvSerie/app/models/serial.rb
class Serial < ApplicationRecord
	belongs_to :user
	has_many :reviewses, dependent: :destroy
	has_many :chapters, dependent: :destroy
	has_many :noticions, dependent: :destroy
  #def self.filter(filter)
    #if filter[0]
    #  where(genero: filter[0])
    #elsif filter[1]
    #  where(ano: filter[1])
   # end
  #end
end

TvSerie/app/controllers/serials_controller.rb
class SerialsController < ApplicationController
  before_action :set_serial, only: [:show, :edit, :update, :destroy]

  # GET /serials
  # GET /serials.json
  def index
    @serials = Serial.all
  end

  # GET /serials/1
  # GET /serials/1.json
  def show
    if @serial.chapters.blank?
      @serial.rating = 0
    else
      @serial.rating = @serial.chapters.average(:rating).round(2)
    end
    @serial.save
  end

  # GET /serials/new
  def new
    if current_user != nil 
      if current_user.parent == nil
        @serial = Serial.new
      else
        redirect_to serials_path, notice: 'Usted es un niño, no puede agregar series'
      end
    else
      authenticate_user!
    end
  end

  # GET /serials/1/edit
  def edit
    if current_user != nil
      if current_user != @serial.user and current_user.admin != true
        redirect_to serials_path, notice: 'Usted no es el creador, no puede editarlo'
      end
    else
      redirect_to serials_path, notice: 'Usted no esta loggeado, no puede editarlo' 
    end
  end

  # POST /serials
  # POST /serials.json
  def create
    @serial = Serial.new(serial_params)
    @serial.user_id = current_user.id
    @serial.rating = 0

    respond_to do |format|
      if @serial.save
        format.html { redirect_to @serial, notice: 'Serial was successfully created.' }
        format.json { render :show, status: :created, location: @serial }
      else
        format.html { render :new }
        format.json { render json: @serial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /serials/1
  # PATCH/PUT /serials/1.json
  def update
    respond_to do |format|
      if @serial.update(serial_params)
        format.html { redirect_to @serial, notice: 'Serial was successfully updated.' }
        format.json { render :show, status: :ok, location: @serial }
      else
        format.html { render :edit }
        format.json { render json: @serial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /serials/1
  # DELETE /serials/1.json
  def destroy
    if current_user != nil
      if current_user == @serial.user or current_user.admin == true
        @serial.destroy
        redirect_to serials_path, notice: 'Serial was successfully destroyed.' 
      else
        redirect_to serials_path, notice: 'Usted no es el creador, no puede destruirlo' 
      end
    else
      redirect_to serials_path, notice: 'Usted no es el creador, no puede destruirlo' 
    end
  end
  
  def search
    s1 = filtrar_genero(params)
    s2 = filtrar_año(params, s1)
    s3 = filtrar_rating(params,s2)
    @serials = filtrar_titulo(params, s3)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_serial
      @serial = Serial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def serial_params
      params.require(:serial).permit(:genero, :ano, :titulo, :descripcion, :rating)
    end
end

def filtrar_genero(params)
  if params[:genero_serial] != '-'
    s = Serial.where(genero: params[:genero_serial])
  else
    s = Serial.all
  end
  return s
end
def filtrar_año(params , lista)
  if params[:ano_serial] != '-'
    s = lista.select{|serie| serie.ano == params[:ano_serial].to_i}
  else
    s = lista
  end
  return s
end
def filtrar_rating(params, lista)
  if params[:rating_serial] != '-'
    s = lista.select{|serie| serie.rating >= params[:rating_serial].to_i}
  else
    s = lista
  end
  return s
end
def filtrar_titulo(params, lista)
  if params[:palabra_clave] != '-'
    s = lista.select{|serie| serie.titulo.include?(params[:palabra_clave])}
  else
    s = lista
  end
  return s
end

TvSerie/app/helpers/serials_helper.rb
module SerialsHelper
end

TvSerie/app/views/serials/_form.html.erb
<%= form_for(serial) do |f| %>
  <% if serial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(serial.errors.count, "error") %> prohibited this serial from being saved:</h2>

      <ul>
      <% serial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :genero %>
    <%= f.select :genero, ["Accion", "Suspenso", "Drama", "Anime", "Romance", "Terror"] %>
  </div>

  <div class="field">
    <%= f.label :año %>
    <%= f.number_field :ano %>
  </div>

  <div class="field">
    <%= f.label :titulo %>
    <%= f.text_area :titulo %>
  </div>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

TvSerie/app/views/serials/edit.html.erb
<h1>Editing Serial</h1>

<%= render 'form', serial: @serial %>

<%= link_to 'Show', @serial %> |
<%= link_to 'Back', serials_path %>

TvSerie/app/views/serials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Series</h1>

<table>
  <thead>
    <tr>
      <th>Genero</th>
      <th>Año</th>
      <th>Titulo</th>
      <th>Descripcion</th>
      <th>Rating</th>
      <th>Ingresado por:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @serials.each do |serial| %>
      <% if current_user == nil %>
      <tr>
        <td><%= serial.genero %></td>
        <td><%= serial.ano %></td>
        <td><%= serial.titulo %></td>
        <td><%= serial.descripcion %></td>
        <td><%= serial.rating %></td>
        <td><%= serial.user.email %></td>
        <td><%= link_to 'Show', serial %></td>
        <td><%= link_to 'Edit', edit_serial_path(serial) %></td>
        <td><%= link_to 'Destroy', serial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% elsif current_user.parent == nil %>
      <tr>
        <td><%= serial.genero %></td>
        <td><%= serial.ano %></td>
        <td><%= serial.titulo %></td>
        <td><%= serial.descripcion %></td>
        <td><%= serial.rating %></td>
        <td><%= serial.user.email %></td>
        <td><%= link_to 'Show', serial %></td>
        <td><%= link_to 'Edit', edit_serial_path(serial) %></td>
        <td><%= link_to 'Destroy', serial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> 
      <% else %>
        <% if serial.user == current_user.parent %>
          <tr>
            <td><%= serial.genero %></td>
            <td><%= serial.ano %></td>
            <td><%= serial.titulo %></td>
            <td><%= serial.descripcion %></td>
            <td><%= serial.rating %></td>
            <td><%= serial.user.email %></td>
            <td><%= link_to 'Show', serial %></td>
            <td><%= link_to 'Edit', edit_serial_path(serial) %></td>
            <td><%= link_to 'Destroy', serial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Serial', new_serial_path %>

TvSerie/app/views/serials/new.html.erb
<h1>New Serial</h1>

<%= render 'form', serial: @serial %>

<%= link_to 'Back', serials_path %>

TvSerie/app/views/serials/search.html.erb
<%= form_tag(search_serials_path, method: "get") do %>
  <p><%= "Filtre por atributos (dejar - si no considerar)" %></p>
  <p>
  <%= label_tag "Elija genero" %>
  <%= select_tag "genero_serial" , options_for_select(['-',"Accion", "Suspenso", "Drama", "Anime", "Romance", "Terror"])%>
  </p>
  <p>
  <%= label_tag "Elija año" %>
  <%= select_tag "ano_serial", options_for_select(['-']+(1990..2017).to_a) %>
  </p>
  <p>
  <%= label_tag "Elija rating minimo" %>
  <%= select_tag "rating_serial", options_for_select(['-']+(0..5).to_a) %>
  </p>
  <p>
  <%= label_tag "Ingrese palabra clave" %>
  <%= text_field_tag :palabra_clave,  '-' %>
  </p>
  <%= submit_tag "Filter" %>
<% end %>
<% @serials.each do |s| %>
  <li>
  <%= "Titulo :"+ s.titulo %>
  <%= "# Año :"+ s.ano.to_s %>
  <%= "# Rating :"+ s.rating.to_s %>
  </li>
<% end %>

TvSerie/app/views/serials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Genero:</strong>
  <%= @serial.genero %>
</p>

<p>
  <strong>Año:</strong>
  <%= @serial.ano %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @serial.titulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @serial.descripcion %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @serial.rating %>
</p>
<p>
  <strong>Reviews:</strong>
  <%= link_to 'Nuevo Review', new_serial_reviewse_path(@serial) %>
</p>
<p>
  <% @serial.reviewses.each do |reviewse| %>
    <p>
    <%= "Comentario: "+reviewse.comentario %>
    <%= "usuario: " + reviewse.user.email %>
    <%= link_to "Destroy", serial_reviewse_path(@serial,reviewse), method: :delete, data: { confirm: 'Are you sure?' }  %>
    </p>
  <% end %>
</p>
<p>
  <strong>Capitulos:</strong>
  <%= link_to 'Nuevo Capitulo', new_serial_chapter_path(@serial) %>
</p>
<p>
  <% @serial.chapters.each do |chapter| %>
    <p>
    <%= link_to "Capitulo " + chapter.numero.to_s, serial_chapter_path(@serial,chapter) %>
    <%= "descripcion: " + chapter.descripcion %>
    <%= "rating: "+ chapter.rating.to_s %>
    <%= link_to "Editar", edit_serial_chapter_path(@serial,chapter) %>
    <%= link_to "Destroy ", serial_chapter_path(@serial,chapter), method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</p>

<%= link_to 'Edit', edit_serial_path(@serial) %> |
<%= link_to 'Back', serials_path %>