TvSerie/config/routes.rb
Rails.application.routes.draw do
  resources :noticions
  resources :serials do
    collection do
      get 'search'
    end
  end
  resources :serials do
  	resources :reviewses
  end
  resources :serials do
    collection do
      get 'search'
    end
    resources :chapters do
      resources :reviewches
    end
  end
  resources :serials do
    resources :chapters do
        resources :vistos
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "serials#index"
end

TvSerie/app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :user
  belongs_to :serial
  has_many :reviewches, dependent: :destroy
  has_one :visto, dependent: :destroy
end

TvSerie/app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]
  before_action :set_serial

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
    if @chapter.reviewches.blank?
      @chapter.rating = 0
    else
      @chapter.rating = @chapter.reviewches.average(:rating).round(2)
    end
    @chapter.save
  end

  # GET /chapters/new
  def new
    if current_user != nil
      if current_user == @serial.user or current_user.admin==true
        @chapter = Chapter.new
      else 
        redirect_to serial_path(@serial), notice: 'Usted no creo esta serial, no puede agregar capitulo'
      end
    else
      authenticate_user!
    end
  end

  # GET /chapters/1/edit
  def edit
    if current_user != nil
      if current_user != @chapter.user and current_user.admin != true
        redirect_to serial_path(@serial), notice: 'Usted no es el creador, no puede editarlo' 
      end
    else
      authenticate_user!
    end
  end

  # POST /chapters
  # POST /chapters.json
  def create
    if current_user != nil
      @chapter = Chapter.new(chapter_params)
      @chapter.user_id = current_user.id
      @chapter.serial_id = @serial.id
      @chapter.rating = 0
    end
    if @chapter.save
      Visto.create!(chapter_id:@chapter.id)
      redirect_to serial_path(@serial)
    else
      render 'new'
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    if current_user != nil
      if current_user == @chapter.user or current_user.admin == true
        @chapter.destroy
        redirect_to serial_path(@serial), notice: 'Chapter was successfully destroyed.' 
      else
        redirect_to serial_path(@serial), notice: 'Usted no es el creador, no puede destruirlo' 
      end
    else
      redirect_to serial_path(@serial), notice: 'Usted no esta loggeado, no puede destruirlo'
    end
  end

  def sacar
    @chapter.visto.users.delete(current_user)
    redirect_to serial_chapter_path(@serial,@chapter)
  end

  def meter
    @chapter.visto.users.push(current_user)
    redirect_to serial_chapter_path(@serial,@chapter)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end
    def set_serial
      @serial = Serial.find(params[:serial_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:largo, :numero, :descripcion)
    end
end

TvSerie/app/helpers/chapters_helper.rb
module ChaptersHelper
end

TvSerie/app/views/chapters/_form.html.erb
<%= form_for([@serial,@chapter]) do |f| %>
  <% if chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% @chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"> 
    <%= f.label :largo %>
    <%= f.text_field :largo %>
  </div>

  <div class="field">
    <%= f.label :numero %>
    <%= f.number_field :numero %>
  </div>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

TvSerie/app/views/chapters/edit.html.erb
<h1>Editing Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Show', serial_chapter_path(@serial,@chapter) %> |
<%= link_to 'Back', serial_path(@serial)%>

TvSerie/app/views/chapters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chapters</h1>

<table>
  <thead>
    <tr>
      <th>Largo</th>
      <th>Numero</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.largo %></td>
        <td><%= chapter.numero %></td>
        <td><%= chapter.descripcion %></td>
        <td><%= link_to 'Shoow', serial_chapter_path(@serial,chapter) %></td>
        <td><%= link_to 'Edit', edit_serial_chapter_path(@serial,chapter) %></td>
        <td><%= link_to 'Destroy', serial_chapter_path(@serial,chapter), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapter', new_serial_chapter_path(@serial) %>

TvSerie/app/views/chapters/new.html.erb
<h1>New Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Back', serial_path(@serial) %>

TvSerie/app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Largo:</strong>
  <%= @chapter.largo %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @chapter.numero %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @chapter.descripcion %>
</p>
<p>
  <strong>Rating:</strong>
  <%= @chapter.rating %>
</p>
<p>
  <% if @chapter.visto.users.include?(current_user) %>
    <%= link_to "MARCAR NO VISTO", edit_serial_chapter_visto_path(@serial,@chapter,@chapter.visto) %>
  <% else %>
    <%= link_to "MARCAR VISTO", edit_serial_chapter_visto_path(@serial,@chapter,@chapter.visto)%>
  <% end %>
</p>
<p>
  <strong>Reviews:</strong>
  <%= link_to 'Nuevo Review', new_serial_chapter_reviewch_path(@serial,@chapter) %>
</p>
<p>
  <% @chapter.reviewches.each do |reviewch| %>
    <p>
    <%= "Comentario: "+reviewch.comentario %>
    <%= "ususario: "+reviewch.user.email %>
    <%= "rating: "+ reviewch.rating.to_s %>
    <%= link_to "Destroy", serial_chapter_reviewch_path(@serial,@chapter,reviewch), method: :delete, data: { confirm: 'Are you sure?' }  %>
    </p>
  <% end %>
</p>
<p>

<%= link_to 'Edit', edit_serial_chapter_path(@serial,@chapter) %> |
<%= link_to 'Back', serial_path(@serial) %>