TvSerie/config/routes.rb
Rails.application.routes.draw do
  resources :noticions
  resources :serials do
    collection do
      get 'search'
    end
  end
  resources :serials do
  	resources :reviewses
  end
  resources :serials do
    collection do
      get 'search'
    end
    resources :chapters do
      resources :reviewches
    end
  end
  resources :serials do
    resources :chapters do
        resources :vistos
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "serials#index"
end

TvSerie/app/models/visto.rb
class Visto < ApplicationRecord
	belongs_to :chapter
	has_and_belongs_to_many :users
end

TvSerie/app/controllers/vistos_controller.rb
class VistosController < ApplicationController
  before_action :set_visto, only: [:show, :edit, :update, :destroy]
  before_action :set_chapter
  before_action :set_serial

  # GET /vistos
  # GET /vistos.json
  def index
    @vistos = Visto.all
  end

  # GET /vistos/1
  # GET /vistos/1.json
  def show
  end

  # GET /vistos/new
  def new
    @visto = Visto.new
  end

  # GET /vistos/1/edit
  def edit
  end

  # POST /vistos
  # POST /vistos.json
  def create
    @visto = Visto.new(visto_params)


    respond_to do |format|
      if @visto.save
        format.html { redirect_to @visto, notice: 'Visto was successfully created.' }
        format.json { render :show, status: :created, location: @visto }
      else
        format.html { render :new }
        format.json { render json: @visto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vistos/1
  # PATCH/PUT /vistos/1.json
  def update
    #if @visto.users.include?(current_user)
    #  @visto.users.push(current_user)
    #else
    #  @visto.users.delete(current_user)
    #end
    #if @visto.update({users:@visto.users})
    #  redirect_to serial_chapter_path(@serial,@chapter)
    #else
    #  render 'edit'
    #end
  end

  # DELETE /vistos/1
  # DELETE /vistos/1.json
  def destroy
    @visto.destroy
    respond_to do |format|
      format.html { redirect_to vistos_url, notice: 'Visto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visto
      @visto = Visto.find(params[:id])
    end
    def set_chapter
      @chapter = Chapter.find(params[:chapter_id])
    end
    def set_serial
      @serial = Serial.find(params[:serial_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def visto_params
      params.fetch(:visto, {})
    end
end

TvSerie/app/helpers/vistos_helper.rb
module VistosHelper
end

TvSerie/app/views/vistos/_form.html.erb
<%= form_for([@serial,@chapter,@visto]) do |f| %>
  <% if visto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visto.errors.count, "error") %> prohibited this visto from being saved:</h2>

      <ul>
      <% @visto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

TvSerie/app/views/vistos/edit.html.erb
<% if @chapter.visto.users.include?(current_user) %>
  <strong><%= "SE MARCO COMO NO VISTO" %></strong>
  <% @chapter.visto.users.delete(current_user)%>
<% else %>
  <strong><%= "SE MARCO COMO VISTO" %></strong>
  <% @chapter.visto.users.push(current_user)%>
<% end %>
<p><%= link_to 'VOLVER A CAPITULO', serial_chapter_path(@serial,@chapter) %></p>

TvSerie/app/views/vistos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vistos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vistos.each do |visto| %>
      <tr>
        <td><%= link_to 'Show', serial_chapter_visto_path(@serial,@chapter,visto) %></td>
        <td><%= link_to 'Edit', edit_seraio_chapter_visto_path(@serial,@chapter,visto) %></td>
        <td><%= link_to 'Destroy', serial_chapter_visto_path(@serial,@chapter,visto), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visto', new_serial_chapter_visto_path(@serial,@chapter) %>

TvSerie/app/views/vistos/new.html.erb
<h1>New Visto</h1>

<%= render 'form', visto: @visto %>

<%= link_to 'Back', serial_chapter_path(@serial,@chapter)%>

TvSerie/app/views/vistos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_serial_chapter_visto_path(@serial,@chapter,@visto) %> |
<%= link_to 'Back', serial_chapter_path(@serial,@chapter) %>